# in iterm, set left option key to +Esc
set -g default-terminal "screen-256color"

# change prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on

bind | split-window -h
bind - split-window -b

# vi commands
# https://sanctum.geek.nz/arabesque/vi-mode-in-tmux/
set-window-option -g mode-keys vi

# vim-like resizing
# bind-key -r K resize-pane -U 3 
bind-key -r K resize-pane -U
bind-key -r J resize-pane -D
bind-key -r H resize-pane -L
bind-key -r L resize-pane -R

# change indexes to be based at 1
set -g base-index 1
setw -g pane-base-index 1

# quick reload
bind r source-file ~/.tmux.conf \; display "config file loaded."

# kill panes with prefix x
unbind x
bind x kill-pane

# kill session with prefix X
bind X kill-session

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
